repos:
    - repo: local
      hooks:
        - id: black
          name: black
          entry: black .
          language: system
          always_run: true
          pass_filenames: false
        - id: isort
          name: isort
          entry: isort .
          language: system
          always_run: true
          pass_filenames: false
        - id: flake8
          name: flake8
          entry: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          language: system
          always_run: true
          pass_filenames: false
