version: '3'
services:

  app:
    build:
      dockerfile: Dockerfile
      context: '.'
    image: get-currency-api:latest
    environment:
      CACHE_REDIS_ENABLE: "false"
      CACHE_REDIS_URI: redis://redis:6379/0
      APP_PORT: 8080

    ports:
      - "8080:8080"
    command:
      - api
    volumes:
      - type: bind
        source: ./src
        target: /app/src

  redis:
    image: redis
    ports:
      - "6379:6379"

