version: '3'
services:

  app:
    build:
      dockerfile: Dockerfile
      context: '.'
    image: get-currency-api:latest
    environment:
      REDIS_URI: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command:
      - api
    volumes:
      - type: bind
        source: ./src
        target: /app/src

  redis:
    image: redis
    ports:
      - "6379:6379"

