name: Publish on Docker Hub and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_test_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_NAME }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $LOGIN/$NAME:currency-helper-latest

      - name: Run tests
        run: docker run -i --rm $LOGIN/$NAME:currency-helper-latest pytest
