name: Publish on Docker Hub and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_test_and_pub:
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -t $LOGIN/$NAME:currency-helper-latest -f Dockerfile .
      - name: Run tests
        run: docker run -ti --rm $LOGIN/$NAME:${GITHUB_REF:11} pytest
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11} && docker push $LOGIN/$NAME:currency-helper-latest
